import win32con

# Simulation / Physics settings
CHAIN_TOTAL_LEN = 170.0
NUM_LINKS = 14
LINK_LEN = CHAIN_TOTAL_LEN / NUM_LINKS
BALL_RADIUS = 32
BALL_MASS = 24.0
BALL_SPIN_RESPONSE = 0.85
LINK_MASS = 0.22
CURSOR_MASS_BASE = 1.0
CURSOR_SPEED_REF = 5.5
CURSOR_MIN_MASS = 0.12
CURSOR_PULL_GAIN = 0.75
CURSOR_PULL_MAX = 20.0
BALL_CURSOR_DRAG = 0.34
GRAVITY = 0.85
AIR_DAMP_PER_SEC = 0.82
GROUND_BOUNCE = 0.1
GROUND_FRICTION = 0.94
WALL_BOUNCE = 0.55
CONSTRAINT_ITERS = 14
SUBSTEPS = 2
FPS = 100

# Audio Settings
DROP_IMPACT_MIN = 3.2
DROP_SOUND_COOLDOWN = 130
CHAIN_SOUND_MIN = 0.65
CHAIN_SOUND_COOLDOWN = 75

# Derived constants
AIR_DAMP = AIR_DAMP_PER_SEC ** (1.0 / (FPS * SUBSTEPS))

# Graphics and Window dimensions
FRAME_W = 384
FRAME_H = 384

# Key Codes for Exiting
QUIT_VKS = (win32con.VK_CONTROL, win32con.VK_SHIFT, ord("Q"))
EXIT_VK = win32con.VK_ESCAPE
VK_LCONTROL = 0xA2
VK_RCONTROL = 0xA3
